# Generated by Django 5.2.13 on 2026-04-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_no", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("raw_data", models.JSONField()),
                ("source", models.CharField(default="source_1", max_length=50)),
            ],
        ),
    ]
